name: nutrition_kit
description: Nutrition domain models and utilities for Assistente Alimentare.
version: 0.1.0
publish_to: 'none'

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  core_kit:
    path: ../core_kit
  path: 1.9.0

dev_dependencies:
  test: 1.25.2
