name: CI

on:
  push:
    branches: [ main, master ]
  pull_request:

jobs:
  flutter:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: stable

      - name: Flutter pub get
        working-directory: app
        run: flutter pub get

      - name: Build runner
        working-directory: app
        run: |
          dart run build_runner build -d || echo "build_runner non configurato o nessuna build necessaria."

      - name: Flutter analyze
        working-directory: app
        run: flutter analyze

      - name: Flutter test
        working-directory: app
        run: flutter test
